services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-demo}
      POSTGRES_USER: ${POSTGRES_USER:-demo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demo123}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-desarrollo-local-no-usar-en-produccion}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_LOG_LEVEL: INFO
      DB_ENGINE: postgres
      DB_NAME: demo
      DB_USER: demo
      DB_PASSWORD: ${POSTGRES_PASSWORD:-demo123}
      DB_HOST: db
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
