sonar.projectKey=DominatorJeca_devops-test-practice-python
sonar.organization=javier-castro

sonar.sources=api,demo
sonar.tests=api/tests.py
sonar.exclusions=**/migrations/**,**/staticfiles/**,**/.venv/**,**/tests.py
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
