apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsu-demo

resources:
  - ../../base
  - postgres-statefulset.yaml
  - postgres-service.yaml

images:
  - name: devsu-demo
    newTag: dev

secretGenerator:
  - name: demo-secrets
    literals:
      - DJANGO_SECRET_KEY=local-dev-no-usar-en-produccion
      - DB_PASSWORD=demo123
      - POSTGRES_PASSWORD=demo123

generatorOptions:
  disableNameSuffixHash: true
