apiVersion: batch/v1
kind: Job
metadata:
  name: demo-migrate
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: demo-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: devsu-demo:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: demo-config
            - secretRef:
                name: demo-secrets
          env:
            - name: RUN_MIGRATIONS
              value: "true"
          args: ["echo", "[job] migraciones aplicadas"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
